version: "3"
networks:
  asvsp:
    external: true

services:
  citus:
    image: citusdata/citus:12.1
    container_name: citus
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    ports:
      - "55432:5432"
    volumes:
      - citus_data:/var/lib/postgresql/data
      - ../init:/docker-entrypoint-initdb.d   # pokreće .sql fajlove SAMO prvi put
    networks:
      - asvsp

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"     # http://localhost:5050
    depends_on:
      - citus
    networks:
      - asvsp

volumes:
  citus_data:
